function dxdt = cartPoleDynamics(t, x, F, p)
%MY_ODE
%    DYDT = MY_ODE(T,Y,F,G,M_CART,M_BODY,L)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Feb-2017 22:39:36

m_cart = p.m1;  % (kg) Cart mass
m_body = p.m2;  % (kg) pole mass
g = p.g;  % (m/s^2) gravity
l = p.l;

Y = [x(1,:);x(3,:); x(2,:); x(4,:)];
t3 = Y(3,:);
t2 = cos(t3);
t4 = sin(t3);
t5 = Y(4,:);
t6 = t2.^2;
t7 = m_body+m_cart-m_body.*t6;
t8 = 1.0./t7;
t9 = t5.^2;
dYdt = [Y(2,:);t8.*(F+g.*m_body.*t2.*t4-l.*m_body.*t4.*t9);t5;(t8.*(F.*t2+g.*m_body.*t4+g.*m_cart.*t4-l.*m_body.*t2.*t4.*t9))./l];
dxdt = [dYdt(1,:); dYdt(3,:); dYdt(2,:); dYdt(4,:)];